export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(
	zsh-autosuggestions
	zsh-syntax-highlighting
	colored-man-pages
	command-not-found
	adb
	osx
)

DISABLE_UPDATE_PROMPT=true

HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
	source "$HB_CNF_HANDLER";
fi

source $ZSH/oh-my-zsh.sh

alias p1="ping 1.1.1.1"

eval "$(/opt/homebrew/bin/brew shellenv)"

alias upg="brew update && brew upgrade && mas upgrade && softwareupdate -i -a"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent