export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(
	zsh-autosuggestions
	zsh-syntax-highlighting
	colored-man-pages
	command-not-found
	adb
	macos
)

DISABLE_AUTO_UPDATE=true

source $ZSH/oh-my-zsh.sh

alias p1="ping 1.1.1.1"

eval "$(/opt/homebrew/bin/brew shellenv)"

alias upg="brew update && brew upgrade && mas upgrade && softwareupdate -i -a && omz update"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

c++ () {
	/usr/bin/c++ -o $(echo $@ | sed 's/\.[^.]*$//') $@
}