export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(
	zsh-autosuggestions
	zsh-syntax-highlighting
	colored-man-pages
	command-not-found
	adb
	macos
)

DISABLE_AUTO_UPDATE=true

source $ZSH/oh-my-zsh.sh

$HOME/.enablesudotid.sh

alias p1="ping 1.1.1.1"

alias upg="brew update && brew upgrade && brew cleanup --prune=all && tldr -u && mas upgrade && softwareupdate -i -a && omz update"

alias ipme="curl -s ip.me | tee >(pbcopy)"

alias rnd="cat /dev/urandom | head -n 10 | md5 | tr -d \"\n\r\" | pbcopy"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

c++ () {
	out=$(echo $@ | sed 's/\.[^.]*$//')
	make $@
	./$out
}